In [1]:

from scipy import stats
import pandas as pd
import numpy as np

import scipy

In [2]:
ls

BEML.csv                       Normal Disribution.ipynb
Confidence Interval (1).ipynb  beml_df.csv
Confidence Interval.ipynb      glaxo_df.csv
GLAXO.csv


In [3]:
glaxo_df=pd.read_csv('glaxo_df.csv')

In [4]:
glaxo_df

Date      Date.1    Close      gain
0     2010-01-05  2010-01-05  1616.80 -0.005444
1     2010-01-06  2010-01-06  1638.50  0.013422
2     2010-01-07  2010-01-07  1648.70  0.006225
3     2010-01-08  2010-01-08  1639.80 -0.005398
4     2010-01-11  2010-01-11  1629.45 -0.006312
...          ...         ...      ...       ...
1733  2016-12-26  2016-12-26  2723.50 -0.001283
1734  2016-12-27  2016-12-27  2701.75 -0.007986
1735  2016-12-28  2016-12-28  2702.15  0.000148
1736  2016-12-29  2016-12-29  2727.90  0.009529
1737  2016-12-30  2016-12-30  2729.80  0.000697

[1738 rows x 4 columns]

In [5]:
glaxo_df.shape[0]

1738

In [8]:
glaxo_df_ci = stats.norm.interval(0.95,
 glaxo_df.gain.mean(),
glaxo_df.gain.std())
print( 'Gain at 95% confidence interval is:', np.round(glaxo_df_ci,3))

Gain at 95% confidence interval is: [-0.026  0.027]


In [10]:
beml_df=pd.read_csv('beml_df.csv')

beml_df_ci = stats. norm.interval(0.95,
beml_df.gain.mean(),
beml_df.gain.std())
np.round(beml_df_ci,3)

array([-0.052,  0.052])

# t-distribution

In [12]:
beml_df=pd.read_csv('beml_df.csv')

beml_df_ci = stats. t .interval(0.95,1737,
beml_df.gain.mean(),
beml_df.gain.std())
np.round(beml_df_ci,3)

array([-0.052,  0.052])

In [11]:
glaxo_df.shape

(1738, 4)

In [5]:
glaxo_df=pd.read_csv('glaxo_df.csv')

glaxo_df_ci = stats.t.interval(0.95,1737,
 glaxo_df.gain.mean(),
 glaxo_df.gain.std())
np.round(glaxo_df_ci, 3)

array([-0.026,  0.027])

In [3]:
round(2.78,1)

2.8

In [ ]:
pd.read_sql_query()